{
 "title": "Go",
 "description": "Runtime metrics from Go applications running on K8S",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(go_info, kubernetes_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(go_info{kubernetes_namespace=~\"$namespace\"}, kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\",quantile=\"1\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Bytes allocation rate (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Heap Allocated Bytes",
   "type": "graph",
   "description": "How many bytes of memory is allocated on the Heap for the objects - Reachable heap objects plus unreachable objects, which GC has not yet freed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Existing objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"} - go_memstats_frees_total",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Object allocation rate (/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Next GC bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "graph",
   "description": "How many bytes of memory in total is taken from system by Go.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{kubernetes_pod_name=~\"$pod\", kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}