apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-mtls
spec:
  secretName: prometheus-mtls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  ipAddresses:
  - 34.136.169.13
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
