apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: prometheus-mtls
spec:
  secretName: prometheus-mtls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
  - concourse
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
  - metrics.hush-house.pivotal.io
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io