kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
        - '--config.file=/etc/config/prometheus.yml'
        - '--web.config.file=/etc/config/web_config.yml'
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/config
          readOnly: true
        - name: prometheus-mtls
          mountPath: /etc/config/certs
          readOnly: true
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus
      - name: prometheus-mtls
        secret:
          secretName: prometheus-mtls
