---
dependencies:
- name: concourse
  version: 3.1.0
  repository: file://../../charts/stable/concourse

- name: prometheus
  version: 7.4.5
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: prometheus.enabled

- name: grafana
  version: 1.18.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: grafana.enabled
