apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  {{- if .Values.vault.global.tlsPostgresEnable }}
  postgres.ca: {{ default "" .Values.postgres.ca  | b64enc | quote }}
  postgres-client.crt: {{ default "" .Values.postgres.crt | b64enc | quote }}
  postgres-client.key: {{ default "" .Values.postgres.key | b64enc | quote }}
  {{- end }}
  postgres.ip: {{ default "" .Values.postgres.ip | b64enc | quote }}
  postgres.secret: {{ default "" .Values.postgres.secret | b64enc | quote }}
