---
dependencies:
- name: prometheus
  version: 8.10.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: prometheus.enabled

- name: grafana
  version: 3.3.10
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: grafana.enabled
