{
 "title": "Concourse",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "atc",
    "label": "ATC",
    "query": "label_values(concourse_db_connections, kubernetes_pod_name)"
   },
   {
    "name": "worker",
    "label": "Worker",
    "query": "label_values(concourse_workers_containers, worker)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(concourse_db_connections, kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduling full duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "concourse_scheduling_full_duration_seconds_total{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ pipeline }}"
    }
   ]
  },
  {
   "title": "Loading versions duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "concourse_scheduling_loading_duration_seconds_total{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ pipeline }}"
    }
   ]
  },
  { "title": "Web $atc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "DB Connections ($atc)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_db_connections{kubernetes_pod_name=~\"$atc\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ kubernetes_pod_name }} - {{ dbname }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod_name=~\"$atc\",container_name!=\"POD\",namespace=~\"$namespace\"}[2m])",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "content": "# Aggregate view of worker activity\n\nThis row is intended for the operator to better understand at a glance what is the load that each worker is under at.\n\n**ATTENTION**: For workers that are external to the cluster, K8S metrics (like CPU usage) can't be retrieved - only those that are exported by ATC can be fetched."
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod_name=~\"$worker\",container_name!=\"POD\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_workers_volumes{worker=~\"$worker\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_workers_containers{worker=~\"$worker\",kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{ worker }}"
    }
   ]
  }
 ]
}