{
 "title": "overall",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "atc",
    "label": "ATC",
    "query": "label_values(concourse_db_connections, kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "atc" },
  {
   "title": "DB Connections ($atc)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "concourse_db_connections{kubernetes_pod_name=~\"$atc\"}",
     "legendFormat": "{{ dbname }}"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_workers_containers", "legendFormat": "{{ worker }}" }
   ]
  },
  {
   "title": "Volumes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_workers_volumes", "legendFormat": "{{ worker }}" }
   ]
  }
 ]
}