{
 "title": "Concourse",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(concourse_db_connections, kubernetes_namespace)"
   },
   {
    "name": "atc",
    "label": "ATC",
    "query": "label_values(concourse_db_connections{kubernetes_namespace=~\"$namespace\"}, kubernetes_pod_name)"
   },
   {
    "name": "worker",
    "label": "Worker",
    "query": "label_values(concourse_workers_containers{kubernetes_namespace=~\"$namespace\"}, worker)"
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "About the sections",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "content": "1. **Overall**: not specific to a particular instance, represents the internal work that Concourse as a service performs;\n2. **Web**: per-ATC statistics for throubleshooting ATC problems on both container and application level; and\n3. **Workers**: per-worker container-level statistics.\n\nRegardless of the section you're looking at, you should expect:\n\n- Each panel contains a description associated with it - hover over the `i` icon on the top left of each panel to know more about the metric being kept track of;\n- A threshold that identifies what is considered *good* behavior for such telemetry (if none, see the panel description)\n"
  },
  {
   "title": "Workers section",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "content": "This row is intended for the operator to better understand at a glance what is the load that each worker is under at.\n\nThe metrics displayed there are from the perspective of both the [pod][k8s-pod] and/or container (not the host).\n\n**ATTENTION**: For workers that are external to the cluster, K8S metrics (like CPU usage) can't be retrieved - only those that are exported by ATC can be fetched.\n\n\n[k8s-pod]: https://kubernetes.io/docs/concepts/workloads/pods/pod/\n\n"
  },
  {
   "title": "Contact",
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "content": "At this moment, the environments accessible here are being maintained by the Concourse for PCF team in Toronto.\n\nYou can reach us at the `concourse-pcf` Slack channel."
  },
  {
   "title": "Container resource metrics",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
   "content": "Metrics like memory and CPU usage are always relative to the total amount of resources conceded to the container, thus, \ncontainers without resource limits **don't** have their resources tracked. "
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "q99 response times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.995, sum by(route,le)(rate(concourse_http_responses_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[10m])))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Loading versions duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (team, pipeline) (rate(concourse_scheduling_loading_duration_seconds_total{kubernetes_namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Full scheduling duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (team, pipeline) (rate(concourse_scheduling_full_duration_seconds_total{kubernetes_namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Builds /s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(concourse_builds_finished{kubernetes_pod_name=~\"$atc\",kubernetes_namespace=~\"$namespace\"}[3m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Resource checks /s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (irate(concourse_resource_checks_total{kubernetes_namespace=~\"$namespace\"}[3m]))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "q999 build finish times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(pipeline,team,le)(rate(concourse_builds_duration_seconds_bucket{kubernetes_namespace=~\"$namespace\"}[3m])))"
    }
   ]
  },
  {
   "title": "Schedulings /s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (irate(concourse_scheduling_total{kubernetes_namespace=~\"$namespace\"}[3m]))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Error rate (/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (message) (rate(concourse_error_logs{kubernetes_pod_name=~\"$atc\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "{{ message }}"
    },
    {
     "expr": "sum (rate(concourse_error_logs{kubernetes_pod_name=~\"$atc\",kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Web",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network RX/TX",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (irate(container_network_receive_bytes_total{pod_name=~\"$atc\",namespace=~\"$namespace\",image!=\"\"}[2m])) * 8",
       "legendFormat": "RX: {{ pod_name }}"
      },
      {
       "expr": "sum by (pod_name) (irate(container_network_transmit_bytes_total{pod_name=~\"$atc\",namespace=~\"$namespace\",image!=\"\"}[2m])) * 8",
       "legendFormat": "TX: {{ pod_name }}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (irate(container_cpu_usage_seconds_total{pod_name=~\"$atc\",container_name!=\"POD\",image!=\"\"}[2m])) \n  / \n(sum by (pod_name) (container_spec_cpu_quota{pod_name=~\"$atc\",container_name!=\"POD\",image!=\"\"})/100000)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Memory usage (RSS)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod_name=~\"$atc\",container_name!=\"POD\",container_name!=\"\",namespace=~\"$namespace\"} \n  / \ncontainer_spec_memory_limit_bytes",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "SQL QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(concourse_db_queries_total{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$atc\"}[3m])",
       "legendFormat": "{{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$atc\"}",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{kubernetes_pod_name=~\"$atc\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "DB Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "concourse_db_connections{kubernetes_pod_name=~\"$atc\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{ dbname }}: {{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "HTTP 500 Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(concourse_http_responses_duration_seconds_count{status=~\"5.*\",kubernetes_pod_name=~\"$atc\",kubernetes_namespace=~\"$namespace\"}[30m]) > 0",
       "legendFormat": "{{ route }} - {{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "Locks held",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "concourse_locks_held{kubernetes_pod_name=~\"$atc\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{ kubernetes_pod_name }} - {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage (RSS)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{pod_name=~\"$worker\",container_name!=\"POD\",container_name!=\"\",namespace=~\"$namespace\"} \n  / \ncontainer_spec_memory_limit_bytes",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Volumes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (worker) (concourse_workers_volumes{worker=~\"$worker\",kubernetes_namespace=~\"$namespace\"})",
       "legendFormat": "{{ worker }}"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (worker) (concourse_workers_containers{worker=~\"$worker\",kubernetes_namespace=~\"$namespace\"})",
       "legendFormat": "{{ worker }}"
      }
     ]
    },
    {
     "title": "Network RX/TX",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (irate(container_network_receive_bytes_total{pod_name=~\"$worker\",image!=\"\"}[2m])) * 8",
       "legendFormat": "RX: {{ pod_name }}"
      },
      {
       "expr": "sum by (pod_name) (irate(container_network_transmit_bytes_total{pod_name=~\"$worker\",image!=\"\"}[2m])) * 8",
       "legendFormat": "TX: {{ pod_name }}"
      }
     ]
    },
    {
     "title": "PV Disk Usage",
     "type": "graph",
     "description": "[Persistent Volume][pv] disk utilization as seen by the [Kubelet][kubelet] in the node that runs the Concourse worker [pod][pod].\n\n[pod]: https://kubernetes.io/docs/concepts/workloads/pods/pod/\n\n[pv]: https://kubernetes.io/docs/concepts/storage/persistent-volumes/\n\n[kubelet]: https://kubernetes.io/docs/concepts/overview/components/#kubelet",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"concourse-work-dir-($worker)\"} / kubelet_volume_stats_capacity_bytes)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name) (irate(container_cpu_usage_seconds_total{pod_name=~\"$worker\",container_name!=\"POD\",image!=\"\"}[2m])) \n  / \n(sum by (pod_name) (container_spec_cpu_quota{pod_name=~\"$worker\",container_name!=\"POD\",image!=\"\"})/100000)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  }
 ]
}