{
 "title": "Flight Recorder",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pipelines",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (team) (sum by (pipeline) (flight_recorder_pipelines))"
    }
   ]
  },
  {
   "title": "Teams",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "flight_recorder_teams" }
   ]
  },
  {
   "title": "Resources",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (pipeline) (sum by (team) (flight_recorder_resources))"
    }
   ]
  },
  {
   "title": "Builds (last hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(flight_recorder_builds{status!~\"(started|pending|)\"}[1h]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "pipelines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flight_recorder_pipelines", "legendFormat": "{{ team }}" }
   ]
  },
  {
   "title": "resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (team) (flight_recorder_resources)",
     "legendFormat": "{{ team }}"
    }
   ]
  },
  {
   "title": "worker state",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flight_recorder_workers", "legendFormat": "{{ state }}" }
   ]
  },
  {
   "title": "pending builds (stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flight_recorder_builds{status=\"pending\"}",
     "legendFormat": "{{ team }} {{ pipeline }}"
    }
   ]
  },
  {
   "title": "check containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flight_recorder_containers{type=\"check\",state=\"created\"}",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "put & get & task containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (worker) (flight_recorder_containers{type!=\"check\",state=\"created\"})",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "started builds (stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flight_recorder_builds{status=\"started\"}",
     "legendFormat": "{{ team }} {{ pipeline }}"
    }
   ]
  },
  {
   "title": "builds errored (last hour)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flight_recorder_builds{status=\"errored\"}[1h]) > 0",
     "legendFormat": "{{ team }} {{ pipeline }}"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table size",
     "type": "graph",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "flight_recorder_pg_table_sizes_bytes",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Writes /s",
     "type": "graph",
     "description": "Rows inserted + updated + deleted",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (table) (irate(flight_recorder_pg_table_stat{statistic=\"n_tup_ins\"}[3m]))\n + \nsum by (table) (irate(flight_recorder_pg_table_stat{statistic=\"n_tup_del\"}[3m]))\n +\nsum by (table) (irate(flight_recorder_pg_table_stat{statistic=\"n_tup_upd\"}[3m]))",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Rows fetched /s",
     "type": "graph",
     "description": "Number of live rows fetched by sequential scans + Number of live rows fetched by index scans",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (table) (irate(flight_recorder_pg_table_stat{statistic=\"seq_tup_read\"}[3m])) \n  + \nsum by (table) (irate(flight_recorder_pg_table_stat{statistic=\"idx_tup_fetch\"}[3m]))",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "table size activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "deriv(flight_recorder_pg_table_sizes_bytes[3m])",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Scans /s",
     "type": "graph",
     "description": "Indexed + not indexed",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (table) (irate(flight_recorder_pg_table_stat{statistic=\"seq_scan\"}[3m])) \n  + \nsum by (table) (irate(flight_recorder_pg_table_stat{statistic=\"idx_scan\"}[3m]))",
       "legendFormat": "{{ table }}"
      }
     ]
    }
   ]
  }
 ]
}