{
 "title": "Node Pools",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pool",
    "label": "Node Pool",
    "query": "label_values(kube_node_labels, label_cloud_google_com_gke_nodepool)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_labels{label_cloud_google_com_gke_nodepool=~\"$pool\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"cpu\"}) by (node) \n  / \nsum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"}) by (node)",
     "legendFormat": "{{  node }}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"memory\"}) by (node) \n  / \nsum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"}) by (node)",
     "legendFormat": "{{  node }}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (kubernetes_node) (irate(node_cpu_seconds_total{kubernetes_node=~\"$node\",mode=\"idle\"}[3m])))",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Memory not available",
   "type": "graph",
   "description": "Memory available is estimated by the kernel, as the amount of RAM that can be used by userspace processes, without causing swapping.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{kubernetes_node=~\"$node\"} / node_memory_MemTotal_bytes",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 17 },
     "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam suscipit ante in arcu pulvinar convallis. In viverra semper venenatis. Pellentesque tincidunt imperdiet nisi, eu malesuada felis lacinia eget. In quis dictum lorem, eget pulvinar purus. Integer vel venenatis metus. Proin nunc ante, mattis eget iaculis quis, bibendum ut urna. Phasellus vestibulum est consequat, tincidunt augue a, consectetur purus. Suspendisse venenatis, erat vitae fringilla dignissim, leo felis tincidunt odio, quis viverra arcu dolor semper neque.\n\nMauris euismod odio ipsum, nec egestas leo posuere aliquet. Etiam ultricies dolor eget interdum scelerisque. Phasellus mattis venenatis turpis in ultrices. Integer non mauris mollis, congue nulla a, sollicitudin mauris. Sed venenatis sem egestas, hendrerit turpis eu, imperdiet lorem. Sed gravida ipsum quis mauris molestie laoreet. Curabitur vel facilisis lacus. Cras porttitor augue sed nisl lobortis luctus. Fusce aliquam dictum mattis."
    }
   ]
  }
 ]
}