{
 "title": "Node",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info, node)"
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": "label_values(kube_node_labels{node=\"$node\"}, label_cloud_google_com_gke_nodepool)"
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "content": "This dashboard contains information related to all of the nodes deployed in this cluster as seen by the `node-exporter` pods deployed to them from the `DaemonSet` in the `metrics` namespace.\n\nUsing the dropdown menu above, you can select a specific node that is part of the cluster that you'd like to know more about at the machine-level."
  },
  {
   "title": "Sections",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "content": "Below you can find three sections:\n\n- **info** - presents high-level information about the system, not meant to be presented as a graph;\n- **utilization** - metrics that represent the usage of specific subsystems\n- **saturation** - TODO\n- **error** - TODO"
  },
  {
   "title": "General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
     "format": "s",
     "valueName": "total",
     "targets": [
      {
       "expr": "time() - node_boot_time_seconds{kubernetes_node=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Kubelet Version",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "kube_node_info{node=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Kernel",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "kube_node_info{node=~\"$node\"}"
      }
     ]
    },
    {
     "title": "OS Image",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "kube_node_info{node=~\"$node\"}"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{kubernetes_node=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{kubernetes_node=~\"$node\",mode=\"user\"})"
      }
     ]
    },
    {
     "title": "CPU Requested",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"cpu\"}) \n  / \nsum(kube_node_status_allocatable{node=~\"$node\",resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Memory requested",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{node=~\"$node\",resource=\"memory\"}) \n  / \nsum(kube_node_status_allocatable{node=~\"$node\",resource=\"memory\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - (irate(node_cpu_seconds_total{kubernetes_node=~\"$node\",mode=\"idle\"}[3m]))",
       "legendFormat": "non-idle"
      },
      {
       "expr": "irate(node_cpu_seconds_total{kubernetes_node=~\"$node\",mode!=\"idle\"}[3m])",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Disk throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{kubernetes_node=~\"$node\"}[3m])*8",
       "legendFormat": "rx {{ device }}"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{kubernetes_node=~\"$node\"}[3m])*8",
       "legendFormat": "tx {{ device }}"
      }
     ]
    },
    {
     "title": "Network throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{kubernetes_node=~\"$node\",device=\"eth0\"}[3m])*8",
       "legendFormat": "rx"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{kubernetes_node=~\"$node\",device=\"eth0\"}[3m])*8",
       "legendFormat": "tx"
      }
     ]
    },
    {
     "title": "Write vs Read times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_write_time_seconds_total{kubernetes_node=~\"$node\"}[3m]) * -1",
       "legendFormat": "write {{ device }}"
      },
      {
       "expr": "rate(node_disk_read_time_seconds_total{kubernetes_node=~\"$node\"}[3m])",
       "legendFormat": "read {{ device }}"
      }
     ]
    },
    {
     "title": "Completed IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{kubernetes_node=\"$node\"}[5m])",
       "legendFormat": "rx {{ device }}"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{kubernetes_node=\"$node\"}[5m])",
       "legendFormat": "tx {{ device }}"
      }
     ]
    },
    {
     "title": "Forks /s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_forks_total{kubernetes_node=~\"$node\"}[5m])",
       "legendFormat": "{{ kubernetes_node }}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemAvailable_bytes{kubernetes_node=~\"$node\"} / node_memory_MemTotal_bytes",
       "legendFormat": "available"
      },
      {
       "expr": "node_memory_Cached_bytes{kubernetes_node=~\"$node\"} / node_memory_MemTotal_bytes",
       "legendFormat": "cached"
      },
      {
       "expr": "node_memory_Active_bytes{kubernetes_node=~\"$node\"} / node_memory_MemTotal_bytes",
       "legendFormat": "active"
      },
      {
       "expr": "node_memory_Buffers_bytes{kubernetes_node=~\"$node\"} / node_memory_MemTotal_bytes",
       "legendFormat": "buffers"
      },
      {
       "expr": "node_memory_Slab_bytes{kubernetes_node=~\"$node\"} / node_memory_MemTotal_bytes",
       "legendFormat": "slab"
      },
      {
       "expr": "node_memory_KernelStack_bytes{kubernetes_node=~\"$node\"} / node_memory_MemTotal_bytes",
       "legendFormat": "kernel stack"
      }
     ]
    },
    {
     "title": "Persistent Volume Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - (kubelet_volume_stats_available_bytes{kubernetes_io_hostname=~\"$node\"} / kubelet_volume_stats_capacity_bytes)",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "Disk utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - min(node_filesystem_avail_bytes{kubernetes_node=~\"$node\"} / node_filesystem_size_bytes) by (device)",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Processes state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{kubernetes_node=~\"$node\"}",
       "legendFormat": "blocked"
      },
      {
       "expr": "node_procs_running{kubernetes_node=~\"$node\"}",
       "legendFormat": "running"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relative Load Averages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{kubernetes_node=~\"$node\"} / node:node_num_cpu:sum",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{kubernetes_node=~\"$node\"} / node:node_num_cpu:sum",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{kubernetes_node=~\"$node\"} / node:node_num_cpu:sum",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "Context switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "ops", "label": "per-second" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{kubernetes_node=~\"$node\"}[3m])"
      }
     ]
    },
    {
     "title": "Paging",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pgpgin{kubernetes_node=~\"$node\"}[3m])",
       "legendFormat": "in"
      },
      {
       "expr": "irate(node_vmstat_pgpgout{kubernetes_node=~\"$node\"}[3m])",
       "legendFormat": "out"
      }
     ]
    },
    {
     "title": "Weighted IO Times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_weighted_seconds_total{kubernetes_node=~\"$node\"}[3m])",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  }
 ]
}