{
 "title": "Pod",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_memory_rss, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_memory_rss{namespace=~\"$namespace\"}, pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Requests",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{pod=~\"$pod\",namespace=~\"$namespace\",resource=\"cpu\"}"
      }
     ]
    },
    {
     "title": "CPU Limits",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{pod=~\"$pod\",namespace=~\"$namespace\",resource=\"cpu\"}"
      }
     ]
    },
    {
     "title": "Memory Requests",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests{pod=~\"$pod\",namespace=~\"$namespace\",resource=\"memory\"}"
      }
     ]
    },
    {
     "title": "Memory Limits",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{pod=~\"$pod\",namespace=~\"$namespace\",resource=\"memory\"}"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
       "legendFormat": "{{ container }}"
      }
     ]
    },
    {
     "title": "Created at",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "kube_pod_start_time{pod=~\"$pod\",namespace=~\"$namespace\"} - time()"
      }
     ]
    },
    {
     "title": "Phase",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
     "yaxes": [
      { "format": "short", "label": "in effect" }
     ],
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=~\"$pod\",namespace=~\"$namespace\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (irate(container_fs_writes_bytes_total{pod_name=~\"$pod\", namespace=~\"$namespace\"}[2m])) * 8\n  +\nsum by (pod_name) (irate(container_fs_reads_bytes_total{pod_name=~\"$pod\", namespace=~\"$namespace\"}[2m])) * 8",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (irate(container_cpu_usage_seconds_total{pod_name=~\"$pod\", namespace=~\"$namespace\", container_name!=\"POD\", image!=\"\"}[2m])) \n  / \n(sum by (pod_name) (container_spec_cpu_quota)/100000)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory usage (RSS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod_name=~\"$pod\", namespace=~\"$namespace\", container_name!=\"POD\", container_name!=\"\"} \n  / \ncontainer_spec_memory_limit_bytes",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (irate(container_network_receive_bytes_total{pod_name=~\"$pod\",namespace=~\"$namespace\",image!=\"\"}[2m])) * 8\n  +\nsum by (pod_name) (irate(container_network_transmit_bytes_total{pod_name=~\"$pod\",namespace=~\"$namespace\",image!=\"\"}[2m])) * 8",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}