{
 "title": "Prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "metrics" },
   { "name": "container", "label": "Container", "query": "prometheus-server" },
   {
    "name": "pod",
    "label": "Prometheus Server Pod",
    "query": "label_values(container_memory_rss{namespace=~\"$namespace\",container_name=~\"$container\"}, pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "name",
   "targets": [
    {
     "expr": "kube_pod_info{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"$pod\",namespace=~\"$namespace\",resource=\"memory\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"$pod\",namespace=~\"$namespace\",resource=\"memory\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "in effect" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"$pod\",namespace=~\"$namespace\",resource=\"cpu\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"$pod\",namespace=~\"$namespace\",resource=\"cpu\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }} {{ container }}"
    }
   ]
  },
  { "title": "Application-Specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Samples Appended /s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{job=\"prometheus\"}[5m]))",
     "legendFormat": "samples"
    }
   ]
  },
  {
   "title": "Query Duration (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{ slice }}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (irate(container_cpu_usage_seconds_total{pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"}[5m])) \n  / \n(sum by (pod_name) (container_spec_cpu_quota)/100000)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (irate(container_network_receive_bytes_total{pod_name=~\"$pod\",namespace=~\"$namespace\",image!=\"\"}[5m])) * 8\n  +\nsum by (pod_name) (irate(container_network_transmit_bytes_total{pod_name=~\"$pod\",namespace=~\"$namespace\",image!=\"\"}[5m])) * 8",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"} \n  / \ncontainer_spec_memory_limit_bytes",
     "legendFormat": "working set"
    },
    {
     "expr": "container_memory_cache{pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"} \n  / \ncontainer_spec_memory_limit_bytes",
     "legendFormat": "cache"
    },
    {
     "expr": "container_memory_usage_bytes{pod_name=~\"$pod\", namespace=~\"$namespace\", container_name=~\"$container\"} \n  / \ncontainer_spec_memory_limit_bytes",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "PV Disk",
   "type": "graph",
   "description": "[Persistent Volume][pv] disk utilization as seen by the [Kubelet][kubelet] in the node that runs the Concourse worker [pod][pod].\n\n[pod]: https://kubernetes.io/docs/concepts/workloads/pods/pod/\n\n[pv]: https://kubernetes.io/docs/concepts/storage/persistent-volumes/\n\n[kubelet]: https://kubernetes.io/docs/concepts/overview/components/#kubelet",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"$namespace-$container\"} / kubelet_volume_stats_capacity_bytes)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  }
 ]
}