resources:
- name: hush-house
  type: git
  source:
    uri: https://((github-token))@github.com/cirocosta/hush-house

- name: concourse-image
  type: registry-image
  source:
    repository: concourse/dev

- name: maintenance-image
  type: registry-image
  source:
    repository: cirocosta/charts-maintenance

- name: charts-repository
  type: git
  source:
    uri: https://((github-token))@github.com/concourse/charts
    branch: gh-pages


jobs:
- name: deploy
  plan:
  - aggregate:
    - get: maintenance-image
    - get: concourse-image
      params: {format: oci}
      trigger: true
    - get: charts-repository
      trigger: true
    - get: hush-house
      trigger: true
  - task: run
    image: maintenance-image
    config:
      platform: linux
      inputs:
      - name: hush-house
        path: .
      - name: concourse-image
      run:
        path: /bin/bash
        args:
        - -c
        - -e
        - |
          apk add --update make curl
          mkdir -p ~/.kube

          echo '((values-b64))' | base64 -d >./.values.yml
          echo '((kube-config-b64))' | base64 -d >~/.kube/config

          helm init --client-only
          helm repo remove local
          helm repo add concourse https://raw.githubusercontent.com/concourse/charts/gh-pages
          helm plugin install https://github.com/databus23/helm-diff --version master

          export HELM_FLAGS=--set=concourse.imageDigest=$(cat ./concourse-image/digest)

          make helm-deps
          make diff && echo "No changes!" || { [[ $? == "2" ]] && make upgrade ; }
